#!/bin/bash

if !(type "recpt1" > /dev/null 2>&1); then
  apt update
  apt install -y --no-install-recommends git autoconf automake

  cd /tmp
  git clone https://github.com/stz2012/recpt1.git
  cd recpt1/recpt1
  ./autogen.sh
  ./configure --enable-b25 --prefix /opt
  make
  make install
fi

recpt1 -v