---
locale:
  timezone: "Asia/Tokyo"
  locale: "ja_JP.UTF-8"

cmdline:
  - "cgroup_enable=cpuset"
  - "cgroup_enable=memory"
  - "cgroup_memory=1"
  - "swapaccount=1"

config:
  - { sect: all, opt: dtoverlay, vals: [disable-bt, disable-wifi], stat: present }
  - { sect: all, opt: dtparam, vals: [pwr_led_trigger=heartbeat], stat: present }

swapfile:
  - { opt: CONF_SWAPSIZE, val: 8192, stat: present }
