---
- name: Install packages
  become: true
  ansible.builtin.apt:
    name: "{{ packages }}"
    update_cache: true
    autoclean: true
    autoremove: true
    state: latest

- name: Remove packages
  become: true
  ansible.builtin.apt:
    name: "{{ old_docker_engine }}"
    update_cache: true
    autoclean: true
    autoremove: true
    state: absent